### PR TITLE
GitHub Actions: Build `reef-node` as artifact for Releases

### PR DESCRIPTION
**Pull request by mwarzynski**
What do you think about automating the process of adding `reef-node` binary to the Release artifacts?

### CODE REVIEW

**Comment by mwarzynski** [comment]
Example release: https://github.com/mwarzynski/reef-chain/releases/tag/v13337

**Comment by Netherdrake** [comment]
The `mainnet_genesis.json` cannot be regenerated, as wasm bytecode is not compiled deterministically. The chain will only ever work with the original bytecode provided here:
https://github.com/reef-defi/reef-chain/blob/master/assets/chain_spec_mainnet.json

**Comment by mwarzynski** [comment]
I removed `chain_spec_mainnet.json` from artifacts.

**Comment by Netherdrake** [comment]
No need for artifacts anymore, they are now bundled with the binary.

**Comment by mwarzynski** [comment]
Okay, great!

@Netherdrake Feel free to merge the PR then! :rocket:

**Pull request merged**
