### PR TITLE
Makefile: Misc improvements

### PR DESCRIPTION
**Pull request by mwarzynski**
Firstly, I would like to propose that we don't change the default toolchain in the `make release` command. It is an unexpected behaviour with no information about this side effect. For now, I left TODO to fix it later.
However, if you know how to use a specific toolchain for `cargo build`, then we could do it within this PR.

Secondly, in my opinion `release` target should not delete whole `target` project. It will be a common scenario that developers use `debug` targets which would be completely removed if one would run `release` target. I personally would be rather unhappy to wait another half an hour again to compile everything once again.

Thirdly, we should use the built-in dependencies functionality rather than exec targets as commands (i.e. syntax: `target: dependency`).

### CODE REVIEW

**Comment by Netherdrake** [comment]
This Makefile was written this way so that it prevents me from forgetting about some minor detail.

1.) I'm removing `target/` to avoid any possible cargo caching issues.
2.) The toolchain is swapped automatically to the stable/tested version. I had some issues with newer version. I use latest versions in development otherwise.
3.) The tests are run after cargo-update to catch regressions on the spot.

**Comment by mwarzynski** [comment]
> This Makefile was written this way so that it prevents me from forgetting about some minor detail.

It's not an argument. It should be suitable for everyone, not only you.

> 1.) I'm removing `target/` to avoid any possible cargo caching issues.

What cargo caching issues?

Couldn't we remove just the `target/release`?

> 2.) The toolchain is swapped automatically to the stable/tested version. I had some issues with newer version. I use latest versions in development otherwise.

I assume it's regarding setting the default toolchain system wide. Changing the default version of the toolchain is seriously a wrong thing to do. It's just unacceptable.
There must be a way to pin point the specific version for cargo to use. I will try to find out how to do so later on.

> 3.) The tests are run after cargo-update to catch regressions on the spot.

`cargo-update` should do only the update. You can run the tests separately by using `make test`. You don't have to worry that you will forget to do so and test won't pass -- we have the CI right now, so it shouldn't be possible (assuming you enabled the requirement for passing CI for a PR).

---

Additionally, I don't really appreciate the approach of closing the PRs without having a discussion.

**Comment by mwarzynski** [comment]
```
~ rustup run toolchain --help
rustup-run
Run a command with an environment configured for a given toolchain

USAGE:
    rustup run [FLAGS] <toolchain> <command>...

FLAGS:
    -h, --help       Prints help information
        --install    Install the requested toolchain if needed

ARGS:
    <toolchain>     Toolchain name, such as 'stable', 'nightly', or '1.8.0'. For more information see `rustup help
                    toolchain`
    <command>...

DISCUSSION:
    Configures an environment to use the given toolchain and then runs
    the specified program. The command may be any program, not just
    rustc or cargo. This can be used for testing arbitrary toolchains
    without setting an override.

    Commands explicitly proxied by `rustup` (such as `rustc` and
    `cargo`) also have a shorthand for this available. The toolchain
    can be set by using `+toolchain` as the first argument. These are
    equivalent:

        $ cargo +nightly build

        $ rustup run nightly cargo build
```

I guess `cargo +1.51.0 build ... other args` would work for pin pointing the toolchain for `make release`.

**Comment by mwarzynski** [comment]
> 1.) I'm removing target/ to avoid any possible cargo caching issues.

I Googled caching issues with Cargo and unfortunately got no results. I am just curious: would you please provide any examples of such issues?

> 3.) The tests are run after cargo-update to catch regressions on the spot.

In general, I believe Makefile targets should do only the 'expected' stuff.

If I run the `cargo-update`, then it should do an update and that's it. It's unexpected that targets do anything else (like running tests). You may rename it to `cargo-update-and-run-tests`, because this is what it does.

Similarly, if I do `make release` it's unexpected that it will remove my debug builds -- forcing me to compile the project once again (and lose 30m of time).

**Comment by Netherdrake** [comment]
> Couldn't we remove just the target/release?
Yes, seems better.

> What cargo caching issues?
I've ran into some issues between minor crate updates and incremental builds. It may be silly, but the approach of nuking artifacts worked well for me. As a side effect, it also clears disk space, since `target/debug` can become especially big (100GB+) over time.

**Comment by Netherdrake** [comment]
I closed the issue because the changed version doesn't serve the job as well as the original. Obviously how to organize complexity is subjective, but at some point it has to be shifted somewhere, and I dont see the point in changing things for sake of change.

**Comment by mwarzynski** [comment]
> I've ran into some issues between minor crate updates and incremental builds. It may be silly, but the approach of nuking artifacts worked well for me.

Comment in the Makefile as an explanation why we remove the build files would be great.

> As a side effect, it also clears disk space, since `target/debug` can become especially big (100GB+) over time.

We could simply implement the `make clean` target for clearing the disk space. I don't think the unexpected side effects are a good thing.

> I closed the issue because the changed version doesn't serve the job as well as the original.

Well, okay...

**Pull request closed without merging**
